LP-154: Create settings page
Artheanos/LN-Payments pull request #107
Opened 2022-06-26 18:37 UTC by Artheanos

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-154

### Description

Added settings page

### How did I test it

Manually

2022-06-26 20:13 UTC, oskar117 requested changes
Dobrze by było dodać jakieś testy.

2022-06-26 20:13 UTC, oskar117 commented on webapp/src/pages/userPanel/serverSettings/ServerSettingsPage.tsx
> +          notification('Settings have been updated', 'success')
Te stringi to dobrze chyba wywalić to plików od i18n.

2022-06-27 17:41 UTC, Artheanos commented on webapp/tests/pages/userPanel/serverSettings/ServerSettingsPage.test.tsx
> +    // describe('when the form contains an invalid entry', () => {
Nie mogę zrobić żeby ten test przechodził.

Na stronie widać, że ten case dziala i powinno przechodzic

TODO

2022-06-27 19:08 UTC, oskar117 approved these changes

2022-06-27 19:10 UTC, merged