LP-162: Add generic way to send tokens to downstream systems
Artheanos/LN-Payments pull request #112
Opened 2022-07-07 21:59 UTC by Artheanos

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-162

### Description

Created `TokenDeliveryService` which sends a json `{tokens: [{sequence: "123"}]}` to an url

### How did I test it

Created tests

2022-07-08 16:52 UTC, oskar117 requested changes

2022-07-08 16:52 UTC, oskar117 commented on webservice/src/main/java/pl/edu/pjatk/lnpayments/webservice/payment/service/TokenDeliveryService.java
> +    private boolean sendTokensAndReturnTrueIfResponseIsValid() {
Generalnie nie powinno się takich metod robić, bo to łamanie SRP. uncle bob już by z baseballa bił

2022-07-08 16:52 UTC, oskar117 commented on webservice/src/main/java/pl/edu/pjatk/lnpayments/webservice/payment/service/TokenDeliveryService.java
> +    private Collection<Token> tokens;
dlaczego trzymamy tokeny jako pole? Przecież każdy request będzie miał swoje tokeny, a instancja tego serwisu jest jedna (domyślnie każdy serwis jest singletonem). Lecimy tutaj w problemy z wielowątkowością. Jeżeli zmienna jest potrzebna tylko w odrębie jednego requesta, to nie ma sensu robić z tego pola klasy.

2022-07-08 16:52 UTC, oskar117 commented on webservice/src/main/java/pl/edu/pjatk/lnpayments/webservice/payment/service/TokenDeliveryService.java
> +        return new RestTemplate().postForEntity(propertyService.getTokenDeliveryUrl(), request, String.class);
Jednak nie przywozimy rest template z jakiegoś configa? Trochę marnowanie pamięci tak robić nowy obiekt przy każdym wywołaniu.

2022-07-08 16:52 UTC, oskar117 commented on webservice/src/test/java/pl/edu/pjatk/lnpayments/webservice/payment/service/TokenDeliveryServiceTest.java
> +        mockWebServer = new MockWebServer();
Po pierwsze to test używający serwera powinnien być w PaymentResourceIntegrationTest, bo tam są testy integracyjne dla tego flow. W tej klasie powinny być tylko testy jednostkowe, czyli zależności muszą być pomockowane. Po drugie to już używamy do tego wiremock, więc posiadanie 2 bibliotek jako serwer http do testów jest bez sensu.

2022-07-08 16:55 UTC, Artheanos commented on webservice/src/main/java/pl/edu/pjatk/lnpayments/webservice/payment/service/TokenDeliveryService.java
> +    private Collection<Token> tokens;
a TokenDeliveryService nie jest inicjowany na nowo przy kazdym requescie?

2022-07-08 18:28 UTC, oskar117 commented on webservice/src/main/java/pl/edu/pjatk/lnpayments/webservice/payment/service/TokenDeliveryService.java
> +    private Collection<Token> tokens;
nie

2022-07-08 18:30 UTC, oskar117 commented on webservice/src/main/java/pl/edu/pjatk/lnpayments/webservice/payment/service/TokenDeliveryService.java
> +    private Collection<Token> tokens;
source: https://docs.spring.io/spring-framework/docs/3.0.0.M3/reference/html/ch04s04.html#beans-factory-scopes-singleton

2022-07-10 19:11 UTC, oskar117 requested changes
Ta jedna zmiana i będzie git

2022-07-10 19:11 UTC, oskar117 commented on webservice/src/main/resources/default/application.properties
> +tokenDeliveryUrl=http://localhost:9000/tokens
na starcie url powinno być puste, a gdy jest puste powinniśmy w ogóle nie wysyłać requesta

2022-07-11 19:08 UTC, oskar117 approved these changes

2022-07-11 19:09 UTC, merged