LP-168 Add part about security
Artheanos/LN-Payments pull request #114
Opened 2022-07-09 15:12 UTC by oskar117

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-168

### Description

Added security part to crypto usage section

### How did I test it

builds and looks good

2022-07-10 12:28 UTC, Artheanos approved these changes

2022-07-10 12:28 UTC, Artheanos commented on docs/src/chapters/wizja-crypto.adoc
> +z sejfem. Każda uprawniona osoba może samodzielnie rozdysponować środki bez wiedzy współpracowników.
to nieprawda ze bez wiedzy

2022-07-10 12:28 UTC, Artheanos commented on docs/src/chapters/wizja-crypto.adoc
> +prawdopodobieństwo utraty środków w niekontrolowany sposób jest zerowe.
nie jest zerowe

2022-07-10 12:28 UTC, Artheanos commented on docs/src/chapters/wizja-crypto.adoc
> +możliwości samodzielnego decydowania o dyspozycji środków. Musi to być zawsze decyzja kolektywna. Dodatkowym
musiałem kilka razy przeczytac zeby zrozumiec
mysle ze lepiej by bylo `osoba nie może samodzielnie dysponować środkami`?

2022-07-10 18:54 UTC, oskar117 commented on docs/src/chapters/wizja-crypto.adoc
> +z sejfem. Każda uprawniona osoba może samodzielnie rozdysponować środki bez wiedzy współpracowników.
"bez zgody" będzie ok?

2022-07-10 18:55 UTC, oskar117 commented on docs/src/chapters/wizja-crypto.adoc
> +prawdopodobieństwo utraty środków w niekontrolowany sposób jest zerowe.
"prawie zerowe?"

2022-07-10 18:56 UTC, oskar117 commented on docs/src/chapters/wizja-crypto.adoc
> +możliwości samodzielnego decydowania o dyspozycji środków. Musi to być zawsze decyzja kolektywna. Dodatkowym
done

2022-07-10 20:32 UTC, hulio90 requested changes

2022-07-10 20:32 UTC, hulio90 commented on docs/src/chapters/wizja-crypto.adoc
> +osób. Nic nie stoi na przeszkodzie nieuczciwej osobie posiadającej dostęp do kradzieży bądź nieuczciwego
dostęp do kradzieży? 
"Nic nie stoi na przeszkodzie ,aby nieuczciwa osoba dokonała kradzieży bądź defraudacji środków" 
coś w tym stylu bym napisał

2022-07-10 20:32 UTC, hulio90 commented on docs/src/chapters/wizja-crypto.adoc
> +tradycyjnych walutach, jak i w kryptowalutach. Środki często trafiają na wspólne konto bankowe bądź na adresy
adresy kryptowalut?

2022-07-10 20:32 UTC, hulio90 commented on docs/src/chapters/wizja-crypto.adoc
> +zabezpieczony na możliwość utraty, bądź uszkodzenia urządzenia zawierającego klucze. Dzięki _mnemonic phrase_ będzie
a nie lepiej "... na wypadek utraty"?

2022-07-11 15:50 UTC, oskar117 commented on docs/src/chapters/wizja-crypto.adoc
> +osób. Nic nie stoi na przeszkodzie nieuczciwej osobie posiadającej dostęp do kradzieży bądź nieuczciwego
done

2022-07-11 15:50 UTC, oskar117 commented on docs/src/chapters/wizja-crypto.adoc
> +tradycyjnych walutach, jak i w kryptowalutach. Środki często trafiają na wspólne konto bankowe bądź na adresy
tak, a co innego xd

2022-07-11 17:39 UTC, hulio90 commented on docs/src/chapters/wizja-crypto.adoc
> +tradycyjnych walutach, jak i w kryptowalutach. Środki często trafiają na wspólne konto bankowe bądź na adresy
myślałem że chodzi Ci o portfel

2022-07-11 18:08 UTC, oskar117 commented on docs/src/chapters/wizja-crypto.adoc
> +zabezpieczony na możliwość utraty, bądź uszkodzenia urządzenia zawierającego klucze. Dzięki _mnemonic phrase_ będzie
done

2022-07-11 18:09 UTC, hulio90 approved these changes

2022-07-11 18:26 UTC, merged