LP-144 write webservice subsection of opis realizacji chapter
Artheanos/LN-Payments pull request #125
Opened 2022-07-23 16:43 UTC by oskar117

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-144

### Description

Wrote entire solution description for webservice.

### How did I test it

I've browsed and read each section after writing it. Spelling and grammar mistakes are inevitable

2022-07-30 17:58 UTC, hulio90 requested changes

2022-07-30 17:58 UTC, hulio90 commented on docs/src/sections/solution/webservice/admin.adoc
> +Aby usunąć administratora, należy najpierw pobrać jego obiekt bazy danych. Ważnym krokiem jest sprawdzenie, czy
nie powinno być obiekt **z** bazy danych?

2022-07-30 17:58 UTC, hulio90 commented on docs/src/chapters/slownik-pajec.adoc
> +    TODO
chciałeś to zostawić, czy zapomniałeś?

2022-07-30 17:58 UTC, hulio90 commented on docs/src/sections/solution/webservice/auth.adoc
> +wątków. Na początku wywołanie poddany walidacji zostaje adres email, czyli wykonywane jest sprawdzenie, czy dany email
wywołania*

2022-07-30 17:58 UTC, hulio90 commented on docs/src/sections/solution/webservice/payment.adoc
> +być dostępna tylko dla klas kontrolerów. Model ten się nie przyjął w innych pakietach, gdyż zysk z tego rozwiązania był
Nie bardzo wynika z tego zdania o co Ci chodzi. Chodzi o warstwe? Może lepiej chociaż napisać: "miała być ona ...". 
W ostatnim zdaniu dałbym czas przyszły. "... zysł z tego rozwiązania byłby niewielki, a generowałby dużo nadmiarowego kodu"

2022-07-30 17:58 UTC, hulio90 commented on docs/src/sections/solution/webservice/transaction.adoc
> +Metoda prywatna _validateAndObtainWallet_ sprawdza, czy istnieje aktualnie istniejąca transakcja. Jeżeli nie, to
istnieje istniejąca

2022-07-30 17:58 UTC, hulio90 commented on docs/src/sections/solution/webservice/wallet.adoc
> +wymagana jest nazwa sieci Bitcoin, do której podłączy się biblioteka. Pochodzi ona aktualnie uruchomionego profilu
pochodzi ona *z*

2022-07-30 17:58 UTC, hulio90 commented on docs/src/sections/solution/webservice/wallet.adoc
> +W przypadku automatycznego zamykania odbywa się to zawsze z kooperacyjnie, chyba że kanał jest nieaktywny dłużej
~z~ kooperacyjnie

2022-07-30 17:58 UTC, hulio90 commented on webservice/src/main/java/pl/edu/pjatk/lnpayments/webservice/wallet/service/BitcoinService.java
> -import org.bitcoinj.params.TestNet3Params;
chciałeś te zmiany dołączyć do tego taska?

2022-07-31 10:05 UTC, oskar117 commented on docs/src/sections/solution/webservice/admin.adoc
> +Aby usunąć administratora, należy najpierw pobrać jego obiekt bazy danych. Ważnym krokiem jest sprawdzenie, czy
done

2022-07-31 10:11 UTC, oskar117 commented on docs/src/chapters/slownik-pajec.adoc
> +    TODO
miałem napisać i zapomniałem, done

2022-07-31 10:12 UTC, oskar117 commented on docs/src/sections/solution/webservice/auth.adoc
> +wątków. Na początku wywołanie poddany walidacji zostaje adres email, czyli wykonywane jest sprawdzenie, czy dany email
done

2022-07-31 10:13 UTC, oskar117 commented on docs/src/sections/solution/webservice/payment.adoc
> +być dostępna tylko dla klas kontrolerów. Model ten się nie przyjął w innych pakietach, gdyż zysk z tego rozwiązania był
done

2022-07-31 10:15 UTC, oskar117 commented on docs/src/sections/solution/webservice/transaction.adoc
> +Metoda prywatna _validateAndObtainWallet_ sprawdza, czy istnieje aktualnie istniejąca transakcja. Jeżeli nie, to
done

2022-07-31 10:15 UTC, oskar117 commented on docs/src/sections/solution/webservice/wallet.adoc
> +wymagana jest nazwa sieci Bitcoin, do której podłączy się biblioteka. Pochodzi ona aktualnie uruchomionego profilu
done

2022-07-31 10:15 UTC, oskar117 commented on docs/src/sections/solution/webservice/wallet.adoc
> +W przypadku automatycznego zamykania odbywa się to zawsze z kooperacyjnie, chyba że kanał jest nieaktywny dłużej
done

2022-07-31 10:16 UTC, oskar117 commented on webservice/src/main/java/pl/edu/pjatk/lnpayments/webservice/wallet/service/BitcoinService.java
> -import org.bitcoinj.params.TestNet3Params;
nie chce mi się na taką pierdołę robić taska na tym etapie prac

2022-07-31 11:32 UTC, hulio90 approved these changes

2022-07-31 11:34 UTC, merged