Lp 143 write proces realizacji chapter part 1
Artheanos/LN-Payments pull request #126
Opened 2022-07-28 19:12 UTC by oskar117

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-143

### Description

I've written description of the first 5 sprints.

### How did I test it

Looks great!

2022-07-30 18:20 UTC, hulio90 requested changes

2022-07-30 18:20 UTC, hulio90 commented on docs/src/sections/sprints/analysis_phase.adoc
> +Pierwszy etap realizacji rozpoczął się w październiku 2022, razem z przedmiotem "Projekt Zespołowy". Etap ten
2021*

2022-07-30 18:20 UTC, hulio90 commented on docs/src/sections/sprints/analysis_phase.adoc
> +implementacją projektu. Zdecydowano się zakończyć, dopiero gdy zespół będzie miał wymaganą wiedzę i działający prototyp
nie wiadomo, co zdecydowano się zakończyć

2022-07-30 18:20 UTC, hulio90 commented on docs/src/sections/sprints/sprint_3.adoc
> +to było do przeglądania historii przed administratorów w przyszłości oraz do przesłania tokenów konkretnej osobie.
~przed~ przez administratorów

2022-07-31 10:01 UTC, oskar117 commented on docs/src/sections/sprints/analysis_phase.adoc
> +Pierwszy etap realizacji rozpoczął się w październiku 2022, razem z przedmiotem "Projekt Zespołowy". Etap ten
done

2022-07-31 10:02 UTC, oskar117 commented on docs/src/sections/sprints/analysis_phase.adoc
> +implementacją projektu. Zdecydowano się zakończyć, dopiero gdy zespół będzie miał wymaganą wiedzę i działający prototyp
done

2022-07-31 10:03 UTC, oskar117 commented on docs/src/sections/sprints/sprint_3.adoc
> +to było do przeglądania historii przed administratorów w przyszłości oraz do przesłania tokenów konkretnej osobie.
done

2022-07-31 11:33 UTC, hulio90 approved these changes

2022-07-31 11:37 UTC, merged