LP-207 Write empty parts of opis realizacji chapter
Artheanos/LN-Payments pull request #133
Opened 2022-08-11 19:20 UTC by oskar117

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-207
### Description

Wrote extra parts of "opis realizacji".

### How did I test it

looks g00d

2022-08-12 19:54 UTC, hulio90 requested changes

2022-08-12 19:54 UTC, hulio90 commented on docs/src/chapters/opis-rozwiazania.adoc
> +automatycznie formatować dokumenty, które zapisane są w zwykłych plikach tekstowych. Zespół dzięki temu nie musiał się
zmieniłbym kolejność "Dzięki temu zespół..."

2022-08-12 19:54 UTC, hulio90 commented on docs/src/chapters/opis-rozwiazania.adoc
> +Są to między innymi różnego rodzaju wykresy i rzuty ekranu. Ostatnim folderem zawierającym kod źródłowy dokumentacji
zrzuty ekranu*

2022-08-12 19:54 UTC, hulio90 commented on docs/src/chapters/opis-rozwiazania.adoc
> +Ostatnim folderem w repozytorium projektu jest _devtools_. Zawiera on dodatkowi pliki związane z programami
~dodatkowi~ dodatkowe*

2022-08-12 19:54 UTC, hulio90 commented on docs/src/chapters/opis-rozwiazania.adoc
> +systemy, czyli węzeł sieci Lightning, węzeł sieci Bitcoin oraz bazę danych. Dostępne są trzy pliki _docker-compose_.
~systemy~ systemu*

2022-08-13 10:07 UTC, oskar117 commented on docs/src/chapters/opis-rozwiazania.adoc
> +automatycznie formatować dokumenty, które zapisane są w zwykłych plikach tekstowych. Zespół dzięki temu nie musiał się
done

2022-08-13 10:08 UTC, oskar117 commented on docs/src/chapters/opis-rozwiazania.adoc
> +Są to między innymi różnego rodzaju wykresy i rzuty ekranu. Ostatnim folderem zawierającym kod źródłowy dokumentacji
done

2022-08-13 10:08 UTC, oskar117 commented on docs/src/chapters/opis-rozwiazania.adoc
> +Ostatnim folderem w repozytorium projektu jest _devtools_. Zawiera on dodatkowi pliki związane z programami
done

2022-08-13 10:08 UTC, oskar117 commented on docs/src/chapters/opis-rozwiazania.adoc
> +systemy, czyli węzeł sieci Lightning, węzeł sieci Bitcoin oraz bazę danych. Dostępne są trzy pliki _docker-compose_.
done

2022-08-13 10:42 UTC, hulio90 approved these changes
👍

2022-08-13 10:50 UTC, merged