LP-182 write proces realizacji chapter part 3
Artheanos/LN-Payments pull request #138
Opened 2022-08-16 22:01 UTC by hulio90

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-182

### Description

I wrote last sprints descriptions

### How did I test it

Ok

2022-08-17 10:32 UTC, oskar117 requested changes
Wydaje się że jest w wiele mniej contentu względem rozdziałów które ja pisałem. Można jeszcze sporo dopisać w każdym akapicie. Dodatkowo ja zadania w tabelkach tak sortowałem, aby można było je ładnie opisać w grupach. Masz czas na poprawki do piątku (tak samo jak na rozdział testy).

2022-08-17 10:32 UTC, oskar117 commented on docs/src/sections/sprints/sprint_10.adoc
> +|LP-143|Write "Proces realizacji" chapter - part 1|Aleksander Konieczny|8|Nieukończone
na tym etapie ty byłeś przypisane do tego taska

2022-08-17 10:32 UTC, oskar117 commented on docs/src/sections/sprints/sprint_11.adoc
> +Wcześniejsze plany nie zakładały, że ta iteracja będzie potrzebna, jednak w rzeczywistości wyszło inaczej. Zespół skupił się na zadaniach niewykonanych w poprzednich sprintach. Zaplanowano zajęcie si
Można dopisać dlaczego nie wyszło.

2022-08-17 10:32 UTC, oskar117 commented on docs/src/sections/sprints/sprint_12.adoc
> +Ta iteracja, tak jak i poprzednia nie była wstępnie planowana. Wysiłki zespołu miały skoncentrować się na zagadnieniach związanych z długiem technicznym oraz pracą dyplomową, która w dalszym ciągu wy
nie trzeba ciągle pisać, że nie była planowana. W jednym z poprzednich sprintów napisz że zespół się nie wyrobił i trzeba było zmienić plan.

2022-08-17 10:32 UTC, oskar117 commented on docs/src/sections/sprints/sprint_13.adoc
> +=== Sprint 13 (02.08.2022 - 22.08.2022)
początek daj na 01.08 ()każdy sprint zacznynamy w poniedziałek

2022-08-18 06:12 UTC, hulio90 commented
> 

Co do grupowania zadań, to się zgadzam, układałeś je według etykiet z JIRY czy jak? Jeśli chodzi o ilość tekstu, to moim zdaniem nie ma sensu patrzyć na to pod względem ilości. Nie mamy przecież określonego limitu stron w pracy, żebyśmy musieli lać wodę.
Poprawię błędy

2022-08-20 09:56 UTC, hulio90 commented on docs/src/sections/sprints/sprint_10.adoc
> +|LP-143|Write "Proces realizacji" chapter - part 1|Aleksander Konieczny|8|Nieukończone
poprawiłem

2022-08-20 09:57 UTC, hulio90 commented on docs/src/sections/sprints/sprint_11.adoc
> +Wcześniejsze plany nie zakładały, że ta iteracja będzie potrzebna, jednak w rzeczywistości wyszło inaczej. Zespół skupił się na zadaniach niewykonanych w poprzednich sprintach. Zaplanowano zajęcie si
done

2022-08-20 09:57 UTC, hulio90 commented on docs/src/sections/sprints/sprint_12.adoc
> +Ta iteracja, tak jak i poprzednia nie była wstępnie planowana. Wysiłki zespołu miały skoncentrować się na zagadnieniach związanych z długiem technicznym oraz pracą dyplomową, która w dalszym ciągu wy
poprawione

2022-08-20 09:57 UTC, hulio90 commented on docs/src/sections/sprints/sprint_13.adoc
> +=== Sprint 13 (02.08.2022 - 22.08.2022)
done

2022-08-20 14:47 UTC, oskar117 approved these changes

2022-08-23 14:45 UTC, merged