LP-210 Apply mentors remarks and polish book part 2
Artheanos/LN-Payments pull request #154
Opened 2022-08-29 20:05 UTC by oskar117

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-210

### Description

Remarks from mentor done

2022-08-29 21:55 UTC, hulio90 requested changes

2022-08-29 21:55 UTC, hulio90 commented on docs/src/chapters/opis-rozwiazania.adoc
> +o krokach potrzebnych do zbudowania projektu, jest _makefile_. Jego zawartość pokazana jest w kodzie 155.
a nie pokazana została?

2022-08-29 21:55 UTC, hulio90 commented on docs/src/sections/webservice_solution.adoc
> +jeden katalog, w którym znajduje się kod źródłowy aplikacji. Pokazany jest na rysunku 40.
~jest~ został

2022-08-29 21:55 UTC, hulio90 commented on docs/src/sections/webservice_solution.adoc
> +standardowym układem dla programu Maven<<maven_directories>>. Jego zawartość zaprezentowana jest na rysunku 41.
~jest~

2022-08-29 22:54 UTC, oskar117 commented on docs/src/sections/webservice_solution.adoc
> +standardowym układem dla programu Maven<<maven_directories>>. Jego zawartość zaprezentowana jest na rysunku 41.
done

2022-08-29 22:54 UTC, oskar117 commented on docs/src/sections/webservice_solution.adoc
> +jeden katalog, w którym znajduje się kod źródłowy aplikacji. Pokazany jest na rysunku 40.
done

2022-08-29 22:55 UTC, oskar117 commented on docs/src/chapters/opis-rozwiazania.adoc
> +o krokach potrzebnych do zbudowania projektu, jest _makefile_. Jego zawartość pokazana jest w kodzie 155.
done

2022-08-29 23:19 UTC, oskar117 commented on docs/src/chapters/opis-rozwiazania.adoc
>  .Plik makefile obsługujący budowanie dokumentacji
wspomnieć o dodaniu KP

2022-08-30 02:10 UTC, hulio90 approved these changes

2022-08-30 08:31 UTC, merged