LP-72: Create jwt renewal endpoint
Artheanos/LN-Payments pull request #32
Opened 2022-02-26 19:36 UTC by Artheanos

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-72

Description
New endpoint /auth/renew which returns a new token

How did I test it
most importantly - intergration test

2022-02-26 20:56 UTC, oskar117 requested changes

2022-02-26 20:56 UTC, oskar117 commented on webservice/src/main/java/pl/edu/pjatk/lnpayments/webservice/auth/service/JwtService.java
> +            return null;
Bardzo nie ładnie zwracać nulla. Ja bym zrobił wywołanie isTokenValid na przykład w refresh token, i rzucił wyjątkiem kiedy będzie niepoprawny.

2022-02-26 21:31 UTC, Artheanos commented on webservice/src/main/java/pl/edu/pjatk/lnpayments/webservice/auth/service/JwtService.java
> +            return null;
hmm tego nie chciałem komitować

2022-02-27 11:22 UTC, oskar117 approved these changes

2022-02-27 11:23 UTC, merged