Create Postman collections with all endpoints
Artheanos/LN-Payments pull request #51
Opened 2022-04-10 14:34 UTC by SxLewandowski

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-87

### Description

Created Postman collections for test API

### How did I test it

Import collections in Postman.

2022-04-11 17:09 UTC, oskar117 requested changes
Czy mógłbyś wsadzić wszystkie do jednej kolekcji i po prostu porobić foldery? Ja mam u siebie wiele kolekcji i wolałbym żeby jeden projekt = jedna kolekcja. Dodatkowo lepiej nie dawać spacji w nazwach plików (wszystkie systemy poza windowsem tego nie lubią).

2022-04-11 18:34 UTC, SxLewandowski commented
> Czy mógłbyś wsadzić wszystkie do jednej kolekcji i po prostu porobić foldery? Ja mam u siebie wiele kolekcji i wolałbym żeby jeden projekt = jedna kolekcja. Dodatkowo lepiej nie dawać spacji w nazwach plików (wszystkie systemy poza windowsem tego nie lubią).

poprawione

2022-04-12 16:50 UTC, oskar117 commented on devtools/postman/test_API.postman_collection.json
> +		"name": "test_API",
Możesz jeszcze zmienić nazwę na coś w stylu LNPayments collection?

2022-04-12 16:50 UTC, oskar117 commented on devtools/postman/test_API.postman_collection.json
> +					"name": "get_auth_token",
Totaj lepiej żeby było po prostu login

2022-04-12 17:34 UTC, SxLewandowski commented on devtools/postman/test_API.postman_collection.json
> +		"name": "test_API",
done

2022-04-12 17:34 UTC, hulio90 commented on devtools/postman/test_API.postman_collection.json
> +					"name": "get_auth_token",
done

2022-04-13 13:05 UTC, oskar117 approved these changes

2022-04-13 16:10 UTC, merged