LP-92: Add admin creation form
Artheanos/LN-Payments pull request #52
Opened 2022-04-10 17:57 UTC by Artheanos

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-92

### Description

Created admin create page
Reused validation schema from register page

### How did I test it

Created an admin with it

2022-04-11 17:17 UTC, oskar117 commented
Po logowanie wyświetla się pusty panel (Scieżka /admin-management). Powinno chyba być przekierowanie na quick buy.

2022-04-11 17:18 UTC, oskar117 commented
![image](https://user-images.githubusercontent.com/27137794/162794683-ec8fa52e-1c45-4d31-a6cd-4b624e7dd2ad.png)
Coś tutaj nie pykło xd
+ nie działa paginacja (nie mogę zmienić na 2 wiersze na stronie)

2022-04-11 17:19 UTC, oskar117 commented
Przy panelu dodawania admina nie idziemy w ten sam styl co logowanie itd? Czy robimy teraz takie na cały ekran?

2022-04-11 17:21 UTC, oskar117 requested changes
Coś mało testów xd

2022-04-13 22:12 UTC, Artheanos commented
> Przy panelu dodawania admina nie idziemy w ten sam styl co logowanie itd? Czy robimy teraz takie na cały ekran?

Nie, to jest drugi styl formularza panelowy (tak jak na mockupie)

2022-04-14 21:25 UTC, merged