LP-124: Create login view
Artheanos/LN-Payments pull request #77
Opened 2022-05-08 20:03 UTC by Artheanos

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-124

### Description

Created login view for the mobile app and further initiated the project
Added navigation, storage
No translations for now, I created a task for this https://candybear.atlassian.net/browse/LP-158

### How did I test it

(Replace ip in `loginUrl` in LoginScreen to your PC's local ip)
I ran `yarn start`, opened the app and logged in

2022-05-10 20:06 UTC, oskar117 commented on mobileapp/components/context/UserContext.tsx
> +  const [token, setToken] = useState<string | null>('')
A co z odświerzaniem tokena robimy w sumie? Aplikacja mobilna nie powinna się raczej zbyt często wylogowywać żeby powiadomienia elegancko przychodziły.

2022-05-10 20:06 UTC, oskar117 requested changes
Generalnie elegancja francja. Da radę dodać jeszcze jakieś komentarze i testy. Pamietam z ćwiczeń z pamo że będzie za to sporo punktów.

2022-05-10 20:09 UTC, oskar117 commented on webservice/src/main/resources/application.properties
> +server.address=0.0.0.0
właściwie to po co ta zmiana?

2022-05-10 20:35 UTC, Artheanos commented on mobileapp/components/context/UserContext.tsx
> +  const [token, setToken] = useState<string | null>('')
w tym przypadku nie robilbym odswiezania tokena

2022-05-12 17:07 UTC, oskar117 approved these changes

2022-05-14 09:55 UTC, merged