LP-140 write wizja chapter
Artheanos/LN-Payments pull request #83
Opened 2022-05-15 20:00 UTC by oskar117

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-140

### Description

I've written 4th chapter of the book about technologies and project structure. 

### How did I test it

Build works, pdf looks good

2022-05-16 14:45 UTC, hulio90 requested changes

2022-05-16 14:45 UTC, hulio90 commented on docs/src/chapters/04-wizja.adoc
> +internetowych na część serwerową oraz część prezentacyjną, nie inaczej postanowiliśmy zrobić prezentowanym systemie.
"w prezentoanym systemie"

2022-05-16 14:45 UTC, hulio90 commented on docs/src/chapters/04-wizja.adoc
> +Znaczna większość wykorzystywanych technologii oraz bibliotek opartych jets na licencjach open-source. Pozwala to na
jest* nie jets

2022-05-16 14:45 UTC, hulio90 commented on docs/src/chapters/04-wizja.adoc
> +Zarówno środowisko wdrożeniowe, jak i deweloperskie oparte będą konteneryzacji z użyciem programu Docker. W przypadku
na konteneryzacji*

2022-05-16 14:45 UTC, hulio90 commented on docs/src/chapters/04-wizja.adoc
> +również miał możliwość samodzielnego wdrożenia aplikacji w wybrany przez siebie, jeżeli zajdzie taka potrzeba.
"w wybrany przez siebie" ale nie napisałeś co

2022-05-16 14:45 UTC, hulio90 commented on docs/src/chapters/04-wizja.adoc
> +uruchomienia komponentów bądź z restrykcyjnych wymogów bezpieczeństwa. Aby to umożliwić do pobrania udostępnione będą
albo wywalic ~~z~~, albo zmienic koncówki tych "restrykcyjnych wymogów bezpieczeństwa"
może lepiej dać "udostępnione zostaną..."

2022-05-16 14:45 UTC, hulio90 commented on docs/src/chapters/04-wizja.adoc
> +BitcoinJ::
opis fajny, może dodać jeszcze cos o Javie?

2022-05-16 14:45 UTC, hulio90 commented on docs/src/chapters/04-wizja.adoc
> +Główną różnicą jest fakt, że zawiera on natywne komponenty natywne dla danego urządzenia. Dzięki temu można
2 x dales natywne
"natywne komponenty ~~natywne~~ ..."

2022-05-16 14:45 UTC, SxLewandowski commented on docs/src/chapters/04-wizja.adoc
> +Discord jest aplikacją służącą do komunikacji głosowej oraz przy pomocy wiadomości tekstowej. Używany jako główne
troche zmieniłbym to zdanie, np na coś takiego:
"...komunikacji głosowej, wideokonferencji oraz przesyłania wiadomości tesktowych"

2022-05-16 17:09 UTC, oskar117 commented on docs/src/chapters/04-wizja.adoc
> +internetowych na część serwerową oraz część prezentacyjną, nie inaczej postanowiliśmy zrobić prezentowanym systemie.
przecież git jest xd

2022-05-16 17:15 UTC, oskar117 commented
@SxLewandowski Poprawione

2022-05-17 15:04 UTC, SxLewandowski commented on docs/src/chapters/04-wizja.adoc
> +internetowych na część serwerową oraz część prezentacyjną, nie inaczej postanowiliśmy zrobić prezentowanym systemie.
brakuje "w", jest tylko "prezentowanym systemie"

2022-05-17 15:08 UTC, SxLewandowski approved these changes
dodaj tylko te "w" i można mergować 👍

2022-05-17 15:23 UTC, oskar117 commented on docs/src/chapters/04-wizja.adoc
> +internetowych na część serwerową oraz część prezentacyjną, nie inaczej postanowiliśmy zrobić prezentowanym systemie.
aa dobra, myślałem że chodzi o słowo "prezentoanym"

2022-05-17 15:25 UTC, merged