LP-173 Write social aspects part
Artheanos/LN-Payments pull request #88
Opened 2022-05-28 15:27 UTC by oskar117

Link to the Jira issue
https://candybear.atlassian.net/browse/LP-173

### Description

I wrote social aspects according to the things discussed at SAI.

### How did I test it

Looks g00d.

2022-05-28 16:24 UTC, SxLewandowski requested changes

2022-05-28 16:24 UTC, hulio90 commented on docs/src/sections/social_aspects.adoc
> +można domniemywać, że mogą stanąć się alternatywnym środkiem płatniczym wobec tradycyjnych walut. Tworzony system
powinno być chyba "stać się*". 
"można domniemywać, że moga" chyba lepiej nie powtarzać i w drugiej części zdania dać coś w stylu:
"istnieje szansa, że staną się one alternatywnym środkiem płatniczym wobec tradyjnych walut"

2022-05-28 16:24 UTC, hulio90 commented on docs/src/sections/social_aspects.adoc
> +zdecentralizowaną bazą danych. Dowód pracy oraz system imisji środków poprzez wykopywanie nowych bloków z
chciałeś tutaj użyć imisja?

2022-05-28 16:24 UTC, hulio90 commented on docs/src/sections/social_aspects.adoc
> +niemożliwy poprzez ilość mocy obliczeniowej aktualnie z nią związanej. Hakerom bardziej opłaca się wykopywać bloki
tutaj z tym zdaniem jest coś nie tak

2022-05-28 16:24 UTC, hulio90 commented on docs/src/sections/social_aspects.adoc
> +do wartości giełdowej kryptowalut, która bywa bardzo zmienna] Transakcje są jedynie podpisane kluczami prywatnymi,
a nie lepiej brzmi: "podpisywane" ?

2022-05-28 16:24 UTC, SxLewandowski commented on docs/src/sections/social_aspects.adoc
> +za tym idzie, nie ma do kogo się zgłosić w przypadku problemów. W przypadku niezrozumiałej utraty środków nie ma
napisałbym raczej : 
"W przypadku utraty środków wynikającej np z niewiedzy czy też pomyłki..."
bo chyba to miałeś na myśli

2022-05-28 16:24 UTC, SxLewandowski commented on docs/src/sections/social_aspects.adoc
> +Nie ma możliwości nałożenia podatków ani żadnej kontroli nad walutą. Salwador, kraj w Ameryce Łacińskiej postanowił
nie lepiej dać "Ameryce Środkowej"? chociaż Łacińska też jest poprawnie, także jak wolisz w sumie

2022-05-28 16:24 UTC, SxLewandowski commented on docs/src/sections/social_aspects.adoc
> +respektowanym w kwestiach prawnych.
tutaj brakuje jakiegoś słowa, ale nie wiem co chciałeś dokładnie przekazać

2022-05-28 16:24 UTC, SxLewandowski commented on docs/src/sections/social_aspects.adoc
> +powinien opłacić podatek dochodowy od przychodów uzyskanych na sprzedaży tokenów, aczkolwiek nie ma możliwości
~~na~~ "ze sprzedaży"

2022-05-28 16:24 UTC, SxLewandowski commented on docs/src/sections/social_aspects.adoc
> +wysłane do innego serwisu, który będzie mógł wykorzystać je w wybrany przez siebie sposób. W ramach projektu osoby
mogły + mógł w jednym zdaniu. Można spróbować troche zmienić to zdanie.

2022-05-29 08:54 UTC, oskar117 commented on docs/src/sections/social_aspects.adoc
> +niemożliwy poprzez ilość mocy obliczeniowej aktualnie z nią związanej. Hakerom bardziej opłaca się wykopywać bloki
tylko co, plz wyjaśniaj bo dobry z polskiego to ja nie jestem

2022-05-29 09:16 UTC, SxLewandowski commented on docs/src/sections/social_aspects.adoc
> +niemożliwy poprzez ilość mocy obliczeniowej aktualnie z nią związanej. Hakerom bardziej opłaca się wykopywać bloki
może tak to zdanie napisać? 
"Aktualnie moc obliczeniowa sieci jest tak duża, że atak na nią jest praktycznie niemożliwy"

2022-05-29 10:37 UTC, SxLewandowski approved these changes

2022-05-29 10:37 UTC, hulio90 commented on docs/src/sections/social_aspects.adoc
> +kryptowaluty miały szybko być prawnie uregulowanym środkiem płatniczym.
dałbym raczej ".. miały szybko ~~być~~ stać się prawnie uregulowanym środkiem płatniczym"

2022-05-29 10:40 UTC, merged